const api = {
    Login: '/oauth/auth',
    UserInfo: '/v1/account/profile',
    Pwd: '/v1/account/pwd',
    Menu: '/v1/account/menu',
    Cls: '/v1/bus/cls/list',
    Inv: '/v1/bus/inv/list',
    SInv: '/v1/bus/inv/listbykeyword',
    Dept: '/v1/bus/dept/list',
    Partner: '/v1/bus/partner/list',
    PartnerCls: '/v1/bus/pc/list',
    SubList: '/v1/bus/sub/list',
    SaveSg: '/v1/bus/sub/save',
    ModifySg: '/v1/bus/sub/modify',
    Sub: '/v1/bus/sub/one',
    XjList: '/v1/bus/ask/list',
    PaList: '/v1/bus/ask/partnerasklist',
    Pa: '/v1/bus/ask/partnerask',
    SavePa: '/v1/bus/ask/partnerupdate',
    SavePac: '/v1/bus/ask/partnerupdateconfirm',
    SaveXj: '/v1/bus/ask/save',
    ModifyXj: '/v1/bus/ask/modify',
    Xj: '/v1/bus/ask/one',
    CheckXj: '/v1/bus/ask/check',
    AskRecord: '/v1/bus/ask/record',

    BindList: '/v1/bus/bdlist/list',
    BindWechat: '/v1/bus/bind/wc',
    BindPartner: '/v1/bus/bind/partner',
    BindPerson: '/v1/bus/bind/person',

    UnBindWechat: '/v1/bus/unbind/wc',
    UnBindPartner: '/v1/bus/unbind/partner',
    UnBindPerson: '/v1/bus/unbind/person',

    PartnerConfirm: '/v1/bus/ask/partnerconfirm',
    SendPartner: '/v1/bus/ask/sendpartner',

    DelXj: '/v1/bus/ask/del',
    DelSub: '/v1/bus/sub/del',
    AuditCount: '/v1/bus/audit/count',
    AuditList: '/v1/bus/audit/list',
    AuditInfo: '/v1/bus/audit/info',
    Audit: '/v1/bus/audit/do',
    UnAudit: '/v1/bus/audit/undo',
    AuditAsk: '/v1/bus/ask/audit',
    BaseList: '/v1/bus/base/list',
    PoDetail: '/v1/bus/po/detail',
    SavePo: '/v1/bus/po/save',
    SavePoMuilt: '/v1/bus/po/saveMuilt',
    PoList: '/v1/bus/po/list',
    Po: '/v1/bus/po/one',
    ModifyPo: '/v1/bus/po/modify',
    DelPo: '/v1/bus/po/del',
    AuditPo: '/v1/bus/po/audit',
    UnAuditPo: '/v1/bus/po/unaudit',
    PoRecord: '/v1/bus/po/record',

    SignDetail: '/v1/bus/sign/detail',
    SaveSign: '/v1/bus/sign/save',
    SignList: '/v1/bus/sign/list',
    Sign: '/v1/bus/sign/one',
    ModifySign: '/v1/bus/sign/modify',
    DelSign: '/v1/bus/sign/del',
    AuditSign: '/v1/bus/sign/audit',
    UnAuditSign: '/v1/bus/sign/unaudit',
    SignRecord: '/v1/bus/sign/record',

    BhList: 'v1/bus/bh/list'
}

export default api